DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS labs;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    points INTEGER
);


CREATE TABLE labs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    output TEXT NOT NULL
);

CREATE TABLE submissions (
    author_id INTEGER NOT NULL,
    lab_id INTEGER NOT NULL,
    lang TEXT NOT NULL
);